### PR TITLE
Add author.id to optimisticResponse

### PR DESCRIPTION
**Pull request by lorensr**

### CODE REVIEW

**Comment by lorensr** [comment]
How to manage a step-based tutorial git repo? We have a branch for each step and link to github's /compare/13...14 pages (diff from step 13 to step 14). 

This PR was accepted with "squash & merge", after which branch 13 has diverged, and this is the repository state:

image
image

At this point I can either:

# Merge 13 into 14–18

eg for 14:

```
git checkout 14
git merge 13 --squash
git commit -m "$(git log --reverse --format='- %s' ..13)"
```

image

# Rebase and force push

- Checkout 18
- Rebase, adding the commit at the tip of 13 into the history before 14
- `git branch -f 14 <new hash>` for 14–18

This is what I've been doing so far, but without the added commit (just editing). Not as good for a public project, with people forking earlier and submitting PRs based off of old versions of branches 14-18.

# Alternative

Is there a better system? I'm wondering whether something like what Meteor tutorials does might work? https://github.com/meteor/tutorials#editing-code-snippets

I think they're asking people to rebase, adding their changes to an existing commit, before submitting a PR? I tried this, but the diff was huge—I couldn't tell what changed. @hwillson do you happen to have any advice? 😄

cc @jeresig

**Comment by hwillson** [comment]
Whatever you decide @lorensr, don't do what the Meteor Tutorials did! 😱 Honestly, that structure is a bit of a mess, and has greatly hindered the ability to accept PR's from community contributors. I go into the issues at length here: https://github.com/meteor/tutorials/pull/167#issue-171363785

Long story short, the benefits gained from a step-by-step commit process are not worth the extra maintenance headache they introduce. In the Meteor Tutorials case I still think they'd be better off by just hard coding the code samples (without trying to associate them to a demo app), then just having the completed demo app available. This lets contributors submit content PR's super easily, and PR's for the demo app can be merged in without having to worry about adding changes to specific commits. We haven't gotten around to updating the Meteor Tutorials to follow this structure, but I really hope it gets updated someday!

**Comment by jeresig** [comment]
@hwillson voiced it better than I could - but I think this is absolutely the right approach. Static code for the specific steps, updated as the book is updated, and then the full repo with the full app, contributed to separately.

**Comment by lorensr** [comment]
Thanks Hugh! 

@jeresig the non-static thing Hugh is talking about is the diff of each commit step being inserted by a script into the tutorial. We're already using static code in markdown in the book repo. Using branches for steps instead of commits, along with the first option in my comment above lets contributors submit PRs easily, avoiding the Meteor Tutorials issue. I think me having to merge PRs into higher-step branches is worth the benefit of having branches available to checkout for people following along (and of having diffs they can read).

**Pull request merged**
